config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'grams#index'
  resources :grams do
    resources :comments, only: [:create]
    resources :likes, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :message, presence: true, length: { in: 10..140}
  belongs_to :gram
  belongs_to :user
end

app/models/gram.rb
class Gram < ApplicationRecord
  validates :caption, presence: true, length: { in: 6..200 }
  validates :picture, presence: true
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  mount_uploader :picture, PictureUploader

  def as_json( options={} )
    super(options).merge(:likes => self.likes.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :gram
  belongs_to :user
  validates :user_id, uniqueness: { scope: :gram_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :grams, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def render_not_found(status = :not_found)
    if status == :forbidden
      render file: 'public/403.html', status: status
    else
      render file: 'public/404.html', status: status
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def new
    @comment = Comment.new
  end

  def create
    @gram = Gram.find_by_id(params[:gram_id])
    return render_not_found if @gram.blank?
    @gram.comments.create(comment_params.merge(user: current_user))
    redirect_to root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:message)
  end

end

app/controllers/grams_controller.rb
class GramsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  # rescue_from ActiveRecord::RecordNotFound, with: :render_not_found
  # I was using this rescue action until Lesson 15, where I started receiving
  # "undefined method `to_i' for #<ActiveRecord::RecordNotFound0x00"> errors.
  # I tried a number of workarounds in the "render_not_found" method.
  # The fix occurred after adding ".find_by_id" to the instance variable
  # assignments in :show, :edit, :udpate, and :destroy actions.
  # I then went back and instituted conditional page renders based on status.

  # 403 forbidden
  # 404 not_found
  # 422 unprocessable_entity

  def index
    @grams = Gram.all.order('created_at DESC').includes(:comments)
  end

  def new
    @gram = Gram.new
  end

  def create
    @gram = current_user.grams.create(gram_params)
    # Guard clause
    return render :new, status: :unprocessable_entity unless @gram.valid?
    redirect_to root_path
  end

  def show
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
  end

  def edit
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
    return render_not_found(:forbidden) unless @gram.user == current_user
  end

  def update
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
    return render_not_found(:forbidden) unless @gram.user == current_user

    @gram.update_attributes(gram_params)
    return render :edit, status: :unprocessable_entity unless @gram.valid?
    redirect_to root_path
  end

  def destroy
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
    return render_not_found(:forbidden) unless @gram.user == current_user

    @gram.destroy
    redirect_to root_path
  end

  private

  def gram_params
    params.require(:gram).permit(:picture, :caption)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    gram = Gram.find(params[:gram_id])
    current_user.likes.create(gram: gram)
    respond_to do |format|
      format.json do
        render json: gram
      # format.html { redirect_to root_path }
      # format.js
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/grams_helper.rb
module GramsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/grams/_gram-top-bar.html.erb
<% if current_user && current_user == g.user %>
  <%= link_to gram_path(g), method: :delete, data: { confirm: 'Are you sure you want to delete this gram?' }, class: 'gram-edit' do %>
    <i class="fa fa-trash-o" aria-hidden="true"></i>
  <% end %>
  <%= link_to edit_gram_path(g), class: 'gram-edit' do %>
    <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
  <% end %>
  <i data-gram-id="<%= g.id %>" data-liking-user="<%= current_user.email.split('@')[0] %>" class="fa fa-heart-o gram-like heart-me" aria-hidden="true"></i>
<% elsif current_user %>
  <i data-gram-id="<%= g.id %>" data-liking-user="<%= current_user.email.split('@')[0] %>" class="fa fa-heart-o gram-like heart-me" aria-hidden="true"></i>
<% else %>
  <i class="fa fa-heart-o gram-like heart-me" aria-hidden="true"></i>
<% end %>

app/views/grams/edit.html.erb
<div class="container text-center">
  <h2 class="action-header">Edit your Crumb:</h2>
  <%= simple_form_for @gram do |f| %>
    <%= f.input :picture, label: 'Upload a Picture', label_html: { class: 'custom-file-upload' } %>
    <%= f.input :caption %>
    <%= f.submit 'Gram-it!', class: 'input-gram-button' %>
  <% end %>
</div>

app/views/grams/index.html.erb
<div class="container text-center">
  <% if current_user.present? %>
  <p class="index-user-email float-left"><%= current_user.email %></p>
  <p class="add-a-gram">
    <%= link_to new_gram_path do %>
      Add-a-gram <i class="fa fa-plus-square-o" aria-hidden="true"></i>
    <% end %>
  </p>
  <% end %>

  <% @grams.each do |g| %>
    <div class="gram-wrapper">
      <div class="row gram-row">
        <div class="col-6 gram-date">
          <%= time_ago_in_words(g.created_at) %> ago
        </div>

        <div class="col-6 gram-icons">
          <%= render partial: 'gram-top-bar', locals: { g: g }, remote: true %>

          <span class="heart-counter heart-counter-<%= g.id %>"><%= g.likes.count %></span>
        </div>

      </div>
      <div>
        <%= image_tag g.picture, class: 'gram-picture' %>
      </div>
      <div class="gram-bottom-elements">
        <div class="gram-caption">
          <span class="gram-user">
            <%= g.user.email.split('@')[0] %>
          </span> <%= g.caption %>
        </div>
        <% if g.comments.present? %>
          <div class="gram-comments-listing">
            <% g.comments.each do |comment| %>
              <div><span class="gram-user">
                <%= comment.user.email.split('@')[0] %>
              </span> <%= comment.message %></div>
            <% end %>
          </div>
        <% end %>
        <div class="gram-comments-input">
          <%= simple_form_for Comment.new, url: gram_comments_path(g) do |f| %>
            <%= f.input :message %>
            <%= f.submit '+', class: 'gram-comment-button' %>
          <% end %>
        </div>
        <div class="clear"></div>
      </div>
    </div>
  <% end %>
</div>

<script>
  $(function() {
    $('.heart-me').click(function( event ) {
      var gramToLike = $( event.target ).data('gram-id');
      $.ajax({
        type: 'POST',
        url: '/grams/' + gramToLike + '/likes'
      }).success(function( data ) {
        console.log(data);
        $('.heart-counter-' + data.id).html(data.likes);
      })

    })
  });
</script>

app/views/grams/new.html.erb
<div class="container text-center">
  <h2 class="action-header">Leave a Crumb:</h2>
  <%= simple_form_for @gram do |f| %>
    <%= f.input :picture, label: 'Upload a Picture', label_html: { class: 'custom-file-upload' } %>
    <%= f.input :caption %>
    <%= f.submit 'Gram-it!', class: 'input-gram-button' %>
  <% end %>
</div>

app/views/grams/show.html.erb
<div class="container text-center">
  <div class="gram-wrapper">
    <div class="row gram-row">
      <div class="col-6 gram-date">
        <%= (@gram.created_at).strftime("%A, %B %d") %>
      </div>
      <div class="col-6 gram-like">
        <i class="fa fa-heart-o" aria-hidden="true"></i>
      </div>
    </div>
    <div>
      <%= image_tag @gram.picture, class: 'gram-picture' %>
    </div>
    <div class="gram-caption">
      <span class="gram-user"><%= @gram.user.email.split('@')[0] %></span> <%= @gram.caption %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grammable</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>

    <header>
      <div class="header-options float-left">
        <%= link_to root_path do %>
          <%= image_tag('graham-icon.png', size: '50x50') %>
          <h1 class="main-header">Gram-Cracker</h1>
        <% end %>
      </div>
      <% if current_user %>
        <div class="user-options float-right">
          <%= link_to 'Log Out', destroy_user_session_path, method: :delete %>
        </div>
        <div class="clear"></div>
      <% else %>
        <div class="user-options float-right">
          <%= link_to 'Sign Up', new_user_registration_path %> or
          <%= link_to 'Log In', new_user_session_path %>
        </div>
        <div class="clear"></div>
      <% end %>
    </header>

    <div class="container">
      <% if notice.present? %>
        <p class="alert alert-info"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
    </div>

    <%= yield %>

  </body>
</html>